import asyncio
import logging
import sys
import os

# Add parent dir to path
sys.path.append(os.path.dirname(os.path.dirname(os.path.abspath(__file__))))

from backend.agents.tutor_agent import TutorAgent
from backend.models.dialogue import DialogueState, DialoguePhase

# Configure Logging
logging.basicConfig(level=logging.INFO, format='%(asctime)s - %(name)s - %(levelname)s - %(message)s')
logger = logging.getLogger("TutorDemo")

# Mock Event Bus and State Manager
class MockEventBus:
    def subscribe(self, topic, handler): pass
    async def publish(self, topic, payload): 
        logger.info(f"EVENT PUBLISHED: {topic} - {payload}")

class MockNeo4j:
    async def run_query(self, query, **kwargs):
        # Mock KG lookup
        if "CourseConcept" in query:
            return [{"c": {
                "name": "SQL_WHERE", 
                "description": "Filters records based on a specified condition",
                "examples": ["SELECT * FROM table WHERE condition"],
                "misconceptions": ["Thinking WHERE works on aggregated data (use HAVING)"]
            }}]
        return []

class MockStateManager:
    def __init__(self):
        self.neo4j = MockNeo4j()

async def run_demo():
    print("\n🚀 STARTING REAL TUTOR CoT DEMO\n" + "="*40)
    
    # 1. Initialize Agent
    agent = TutorAgent("tutor-demo", MockStateManager(), MockEventBus())
    
    # 2. Define Request
    learner_id = "demo_learner_01"
    question = "I don't understand how WHERE works in SQL."
    concept_id = "SQL_WHERE"
    
    print(f"Learner ID: {learner_id}")
    print(f"Concept: {concept_id}")
    print(f"Question: {question}")
    print("-" * 40)
    
    # 3. Execute with FORCE_REAL = True
    print("\n🧠 EXECUTE: Calling TutorAgent with force_real=True...")
    
    result = await agent.execute(
        learner_id=learner_id,
        question=question,
        concept_id=concept_id,
        hint_level=1,
        force_real=True  # <--- CRITICAL
    )
    
    # 4. Analyze Result
    print("\n✅ RESULT RECEIVED:")
    print("-" * 20)
    print(f"Success: {result['success']}")
    print(f"Phase: {result.get('current_phase')}")
    print(f"Guidance:\n> {result['guidance']}")
    
    if "Mock" in result['guidance']:
        print("\n❌ FAILURE: Response appears to be Mocked!")
    else:
        print("\n✅ SUCCESS: Response appears to be generated by Real LLM logic (CoT).")

if __name__ == "__main__":
    asyncio.run(run_demo())
